sudo: required
services:
    - docker

before_install:
    - docker build -t sopizhenko/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sopizhenko/docker-react npm run test -- --coverage